---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  labels: # labels act as a search filter
    app: northwind
    app.kubernetes.io/name: northwind # kubernetes has a standard set of labels
  annotations: # provide management information for custom resources
    # put volume provisioner under annotations
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com

spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
    # G - 1000MB Gi - 1024MB
      storage: 1Gi # 1GB is minimum for digital ocean